### ISSUE TITLE
Typo in Makefile.PL: Weather-Meto -> Weather-Meteo

### ISSUE THREAD

**Issue by eserte** [nigelhorne/Weather-Meteo#1]
Some configuration values in Makefile.PL are spelled as Weather-Meto with a missing "e". See
https://metacpan.org/release/NHORNE/Weather-Meteo-0.02/source/Makefile.PL#L61-74
Consequence is that https://metacpan.org/dist/Weather-Meteo cannot link to the repository or issue tracker correctly.

**Comment by nigelhorne** [comment]
Thanks for the report.
