### ISSUE TITLE
Can't locate Test/Compile.pm in @INC

### ISSUE THREAD

**Issue by eserte** [nigelhorne/Weather-Meteo#2]
t/10-compile.t fails if Test::Compile is not installed (a missing prereq specification?):
```
Can't locate Test/Compile.pm in @INC (you may need to install the Test::Compile module) (@INC contains: ...
BEGIN failed--compilation aborted at t/10-compile.t line 8.
t/10-compile.t ........ 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```
Also undeclared: Test::Requires:
```
Can't locate Test/Requires.pm in @INC (you may need to install the Test::Requires module) (@INC contains: ...
BEGIN failed--compilation aborted at t/unused.t line 13.
t/unused.t ............ 
Dubious, test returned 2 (wstat 512, 0x200)
No subtests run 
```

**Comment by nigelhorne** [comment]
I belive this is already fixed by https://github.com/nigelhorne/Weather-Meteo/commit/9c0eb2776aecb6ca104de57ac6aaaa0658d9f38b  please check

**Comment by eserte** [comment]
This problem does not seem to appear anymore with newer Weather-Meteo versions (checked my 0.03 reports), so I think this is indeed fixed.
