### ISSUE TITLE
Can't locate Geo/Coder/Free.pm in @INC

### ISSUE THREAD

**Issue by eserte** [nigelhorne/Weather-Meteo#4]
t/10-compile.t seems to fail if Geo::Coder::Free is not installed (is this an optional prerequisite?):
```
Can't locate Geo/Coder/Free.pm in @INC (you may need to install the Geo::Coder::Free module) (@INC contains:...
BEGIN failed--compilation aborted at bin/weather line 8.

#   Failed test 'bin/weather compiles'
#   at t/10-compile.t line 12.
# Looks like you failed 1 test of 2.
t/10-compile.t ........ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
```

**Comment by nigelhorne** [comment]
G:C:Free is not actually used anywhere within W:Meteo.  It is, however, used in a sample program "bin/weather".  I'm yet to change T:Compile that it's not needed by the library but it is needed by the sample program (it's the argument to all_files_ok - a simple change which I'll put in the next release)
